version: '3.7'
services:
  ls:
    image: khlebtsov/kofify-db:v1
    container_name: kofify-db
    restart: always
    environment:
      MYSQL_DATABASE: 'kofify'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '2345:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - kofify-db:/var/lib/mysql
  activemq:
    image: webcenter/activemq:5.14.3
    container_name: kofify-activemq
    ports:
      - "8162:8161"
      - "61617:61616"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "password"
# Names our volume
volumes:
  kofify-db: