logging:
  level:
    org:
      apache:
        http: trace
      springframework:
        web: trace
#    logging.level.org.apache.http=trace
#    logging.level.org.apache.http.wire=trace
#    logging.level.org.springframework.web=trace
## MULTIPART (MultipartProperties)
# Enable multipart uploads

# Threshold after which files are written to disk.
spring:
  datasource:
    url: jdbc:h2:mem:default;Mode=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=TRUE;
    platform: h2
    continue-on-error: true
    #spring.datasource.username=sa
    #spring.datasource.password=
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: /Users/alexey/IdeaProjects/imgs
image:
  maxWidth: 1200
  maxHeight: 1600
  profileMaxWidth: 500
  profileMaxHeight: 500

push:
  secret: MWFhMDUyMDUtMjE5Ny00MWI1LTg2MmUtNjE1Y2E3MzY2YmRl
  app-id: 700f900e-f399-44e4-800d-5fc23f769dbc
  it-invitation-title: Kofify
  en-invitation-title: Kofify
  it-invitation-content: "{0} ti ha invitato a prendere un caffè"
  en-invitation-content: "{0} has invited you for a cup of coffee"
